### ISSUE TITLE
TorrentGetAll fails with Transmission 4

### ISSUE THREAD

**Issue by fabiocody** [hekmon/transmissionrpc#19] opened 2023-03-12 10:46 UTC
The error is `'torrent-get' rpc method failed: can't unmarshall request answer body: json: cannot unmarshal bool into Go struct field torrentGetResults.arguments.torrents of type int64`

I call it as `torrents, err := transmission.TorrentGetAll(context.TODO())`

Everything was working fine until I updated to Transmission 4

**Comment by hekmon** [comment] 2023-03-12 11:04
That was more or less expected for transmission major version upgrade.

As the README states, this lib follows the [RPC v16 version](https://github.com/hekmon/transmissionrpc#transmissionrpc) (with retrocompatibility on the v15 version). Transmission v4 seems to have switched to [RPC version 17](https://github.com/transmission/transmission/blob/4.0.0/docs/rpc-spec.md#5-protocol-versions) which this lib does not support (yet ?).

To be honest I have very little free time at the moment and I am not using Transmission anymore. Chances that I implement a new major version of the lib are quite low. Technically this is not a bug because of the explicit RPC version support stated in the README but I will leave this open as a feature request in case I start working on it or someone opens a PR.

I might update the readme to warn people of the incompatibility tho. Thank you for bringing that up.

**Comment by GianniBYoung** [comment] 2023-03-17 00:36
> That was more or less expected for transmission major version upgrade.
> 
> As the README states, this lib follows the [RPC v16 version](https://github.com/hekmon/transmissionrpc#transmissionrpc) (with retrocompatibility on the v15 version). Transmission v4 seems to have switched to [RPC version 17](https://github.com/transmission/transmission/blob/4.0.0/docs/rpc-spec.md#5-protocol-versions) which this lib does not support (yet ?).
> 
> To be honest I have very little free time at the moment and I am not using Transmission anymore. Chances that I implement a new major version of the lib are quite low. Technically this is not a bug because of the explicit RPC version support stated in the README but I will leave this open as a feature request in case I start working on it or someone opens a PR.
> 
> I might update the readme to warn people of the incompatibility tho. Thank you for bringing that up.

Thanks for updating the read me, I have been working on a tui using this library and was wondering/hoping it would be able to support transmission 4. 

Regardless of if you get around to updating it, I appreciate the work you've put into the current version and its been a pleasure to work with this project!

**Comment by hekmon** [comment] 2023-03-17 12:30
Thank you for your kind words @GianniBYoung !

I hope someone will pick up (PR or fork) the lib. And may be Transmission v4 will be so good that I will use it again in the future ! (therefor I will release a v3). But to be honest, with my newborn child, it won't be anytime soon :)

**Comment by GianniBYoung** [comment] 2023-03-21 23:51
After doing some quick testing with transmission-4.02 I didn't encounter this error. 

My understanding is that they changed one of the fields to use bools instead of ints. More info in this [issue](https://github.com/transmission/transmission/pull/5170).

It looks like the transmission version increase from 16 to 17 shouldn't include any breaking changes (above issue aside) and 4.0 might still be compatible with this project with minor improvements. 

[Transmission Rpc version docs](https://github.com/transmission/transmission/blob/4.0.0/docs/rpc-spec.md#5-protocol-versions)

**Comment by tubbo** [comment] 2023-04-13 19:08
@hekmon FWIW this lib has been working fine for me (through `autobrr`), it appears that this may be the only incompatibility so far. there are missing things from the RPC implementation here but other than that I'm not getting any weird errors in my client.

Working on a patch right now for adding labels to the `TorrentAddPayload`, but I can try to see if I can work out the incompatibility here as well.

**Comment by KyleSanderson** [comment] 2023-04-14 05:56
> @hekmon FWIW this lib has been working fine for me (through `autobrr`), it appears that this may be the only incompatibility so far. there are missing things from the RPC implementation here but other than that I'm not getting any weird errors in my client.
> 
> Working on a patch right now for adding labels to the `TorrentAddPayload`, but I can try to see if I can work out the incompatibility here as well.

If you do want to extend the transmission implementation in autobrr (I actually stumbled upon this by chance lol)... that would also be appreciated 😸. I took a stab at it a while ago then lost steam from other issues in my flow. Happy to collab on discord / whatever to get it up to parity.

**Comment by hekmon** [comment] 2023-04-14 19:14
That is great news @tubbo ! Thanks you for stepping in to keep this lib alive 😊 

I won't be able to test your fix for the reason I have stated earlier on this issue but here is what we can do: send a PR with your patch, have some folks (from this issue may be ?) test it and if several validate the changes, I will merge it and release a v3 (I like to change semver major version for RPC version change, it keeps everything simpler for everyone).\

Also it seems that they [reverted one of the incompatibility](https://github.com/transmission/transmission/pull/5170) (thx @GianniBYoung ). Does anyone tested it ?

**Comment by hyperreal64** [comment] 2023-04-14 21:55
> @hekmon FWIW this lib has been working fine for me (through `autobrr`), it appears that this may be the only incompatibility so far. there are missing things from the RPC implementation here but other than that I'm not getting any weird errors in my client.
> 
> Working on a patch right now for adding labels to the `TorrentAddPayload`, but I can try to see if I can work out the incompatibility here as well.

Same here. I've added the new labels, removed the deprecated ones, and am now working on implementing the group-set and group-get methods for bandwidth groups. You can see my changes at https://github.com/hyperreal64/transmissionrpc.

**Comment by hyperreal64** [comment] 2023-04-14 21:59
Would removing the deprecated labels break backwards compatibility with Transmission 3?

**Comment by hekmon** [comment] 2023-04-15 16:12
> Would removing the deprecated labels break backwards compatibility with Transmission 3?

I will let others answer that but that is not an issue on my side: each Transmission RPC version translate to a major semver on this lib.

**Comment by hekmon** [comment] 2023-04-17 12:28
@fabiocody @fabiocody @tubbo can I kindly ask you guys to check out and test the code proposed by @hyperreal64 in #21 ? As I am unable to test it myself, if you can confirme this PR works I will merge it and tag a new v3 :)

Thank you all for your time and implication while I am unable to do so for now 🙏

**Comment by davidnewhall** [comment] 2023-06-11 20:11
I'm about to add a Transmission dashboard integration to Notifiarr using this library. Just throwing it out there in case you need more testers. I have two more here https://github.com/Notifiarr/notifiarr/issues/488

EDIT: I'm trying to figure out how to bring that fork into my project without a replace directive so it can build in GH actions. I'm probably missing something simple. Open to suggestions.

EDIT2: This works; in go.mod, and will presumably work in a GH action build. 🤞 
```
replace github.com/hekmon/transmissionrpc => github.com/hyperreal64/transmissionrpc v0.0.0-20230416162540-2445f445c709
```

**Comment by davidnewhall** [comment] 2023-06-16 06:40
Testing with Transmission 4.0.3 (6b0e49bbb2) on macOS, using `TorrentGetAll` against `master` branch of this repo does not produce an error. I also tested the changes @hyperreal64 gave us in #21. No errors, and the output seems to be compatible. I test it by cloning his repo locally and using a local override `=> ../transmissionrpc`. I also [pasted in a new struct and entry method](https://github.com/hekmon/transmissionrpc/pull/24/files#diff-cc5d2cdea66aa1021f86124b6b59590af4179f66c5da18e04c43ae82c0b6bfbdR49-R86) to make it easy on myself. The other method my code tests is `SessionArgumentsGetAll`, which also seems fine and produces no errors. This is [my change that does the test](https://github.com/Notifiarr/notifiarr/pull/536/files#diff-04af1a04f0098c0e68d73ba041ee9dd102b9ea9ce430e7be4482b54317cac7d0R39) for anyone interested.

I only have two torrents in my app.  If there are any specific downloads I should test or methods I should try running, I'm down to do more poking. Seems good though.

**Comment by hekmon** [comment] 2023-08-11 16:40
Closing as [TransmissionRPC v3](https://github.com/hekmon/transmissionrpc/releases/tag/v3.0.0-beta1) is out as beta. Please open dedicated issues if you encounter anything with this new release.

**Closed as completed by hekmon** 2023-08-11 16:40 UTC
